version: '3.5'

services:
  api:
    build:
      context: .
    command: billing-api
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
