version: '3.5'

services:
  api:
    build:
      context: .
    environment:
      BILLING_DB_DSN: postgres://postgres:postgres@db:5432/billing?sslmode=disable
      BILLING_DB_DSN_TEST: postgres://postgres:postgres@db:5432/billing-test?sslmode=disable
      BILLING_SESSION_COOKIE_NAME: sessionid
    command: billing-api
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
